/**:
  ros__parameters:
    dt: 0.05

    LQR_params:
      q_surge: 40
      q_pitch: 80
      q_yaw: 80

      r_surge: 0.4
      r_pitch: 0.6
      r_yaw: 0.6

      i_surge: 0.2
      i_pitch: 0.2
      i_yaw: 0.2

      i_weight: 0.5

    inertia_matrix: [53.7, 0.0, 0.0, 0.0, 23.1128, 0.1025, 0.0, 0.1025, 26.23998]

    #Clamp parameter
    max_force: 80
