/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) auv_model_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {9, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {12, 1, 1};

/* auv_model_expl_vde_adj:(i0[9],i1[9],i2[3],i3[0])->(o0[12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28;
  a00=-30.;
  a01=arg[0]? arg[0][1] : 0;
  a02=3.0075286497147785e-01;
  a03=arg[1]? arg[1][5] : 0;
  a02=(a02*a03);
  a04=-5.4600502730695923e-04;
  a05=arg[1]? arg[1][4] : 0;
  a06=(a04*a05);
  a02=(a02+a06);
  a06=-4.9042367722181902e-06;
  a07=arg[1]? arg[1][3] : 0;
  a06=(a06*a07);
  a02=(a02+a06);
  a06=5.5581350085139543e-06;
  a08=arg[1]? arg[1][2] : 0;
  a06=(a06*a08);
  a02=(a02+a06);
  a06=-3.0184487502609172e-03;
  a09=arg[1]? arg[1][1] : 0;
  a06=(a06*a09);
  a02=(a02+a06);
  a06=-6.0150572994295574e-03;
  a10=arg[1]? arg[1][0] : 0;
  a06=(a06*a10);
  a02=(a02+a06);
  a06=(a01*a02);
  a06=(a00*a06);
  a11=30.;
  a12=(a11*a01);
  a13=(a12*a02);
  a06=(a06+a13);
  a13=arg[0]? arg[0][2] : 0;
  a04=(a04*a03);
  a14=3.0257778596593993e-01;
  a14=(a14*a05);
  a04=(a04+a14);
  a14=2.7177645446042520e-03;
  a14=(a14*a07);
  a04=(a04+a14);
  a14=-3.0801331505514837e-03;
  a14=(a14*a08);
  a04=(a04+a14);
  a14=6.0570157695918683e-03;
  a14=(a14*a09);
  a04=(a04+a14);
  a14=1.0920100546139184e-05;
  a14=(a14*a10);
  a04=(a04+a14);
  a14=(a13*a04);
  a14=(a11*a14);
  a06=(a06+a14);
  a14=(a00*a13);
  a15=(a14*a04);
  a06=(a06+a15);
  a15=arg[0]? arg[0][4] : 0;
  a16=5.5581350085139340e-06;
  a16=(a16*a03);
  a17=-3.0801331505514781e-03;
  a17=(a17*a05);
  a16=(a16+a17);
  a17=-2.9967785627100469e-02;
  a17=(a17*a07);
  a16=(a16+a17);
  a17=3.3963490377380855e-02;
  a17=(a17*a08);
  a16=(a16+a17);
  a17=-6.1658244361114702e-05;
  a17=(a17*a09);
  a16=(a16+a17);
  a17=-1.1116270017027866e-07;
  a17=(a17*a10);
  a16=(a16+a17);
  a17=(a15*a16);
  a17=(a00*a17);
  a06=(a06+a17);
  a17=arg[0]? arg[0][5] : 0;
  a18=-3.0184487502609133e-03;
  a18=(a18*a03);
  a19=6.0570157695918657e-03;
  a19=(a19*a05);
  a18=(a18+a19);
  a19=5.4404333259807062e-05;
  a19=(a19*a07);
  a18=(a18+a19);
  a19=-6.1658244361114783e-05;
  a19=(a19*a08);
  a18=(a18+a19);
  a19=3.3484658136227786e-02;
  a19=(a19*a09);
  a18=(a18+a19);
  a19=6.0368975005218254e-05;
  a19=(a19*a10);
  a18=(a18+a19);
  a19=(a17*a18);
  a19=(a11*a19);
  a06=(a06+a19);
  a19=arg[0]? arg[0][0] : 0;
  a20=casadi_fabs(a19);
  a21=-6.0150572994295635e-03;
  a21=(a21*a03);
  a22=1.0920100546139210e-05;
  a22=(a22*a05);
  a21=(a21+a22);
  a22=9.8084735444364535e-08;
  a22=(a22*a07);
  a21=(a21+a22);
  a22=-1.1116270017027936e-07;
  a22=(a22*a08);
  a21=(a21+a22);
  a22=6.0368975005218423e-05;
  a22=(a22*a09);
  a21=(a21+a22);
  a22=3.3453634479321918e-02;
  a22=(a22*a10);
  a21=(a21+a22);
  a20=(a20*a21);
  a06=(a06+a20);
  a20=casadi_sign(a19);
  a22=(a19*a21);
  a20=(a20*a22);
  a06=(a06+a20);
  a20=23.;
  a20=(a20*a21);
  a06=(a06+a20);
  a06=(-a06);
  if (res[0]!=0) res[0][0]=a06;
  a06=(a00*a19);
  a20=(a06*a02);
  a22=(a19*a02);
  a22=(a11*a22);
  a20=(a20+a22);
  a22=-4.9042367722181935e-06;
  a22=(a22*a03);
  a03=2.7177645446042498e-03;
  a03=(a03*a05);
  a22=(a22+a03);
  a03=1.4970303990827358e+00;
  a03=(a03*a07);
  a22=(a22+a03);
  a03=-2.9967785627100754e-02;
  a03=(a03*a08);
  a22=(a22+a03);
  a03=5.4404333259807184e-05;
  a03=(a03*a09);
  a22=(a22+a03);
  a03=9.8084735444363873e-08;
  a03=(a03*a10);
  a22=(a22+a03);
  a03=(a13*a22);
  a03=(a00*a03);
  a20=(a20+a03);
  a03=(a11*a13);
  a10=(a03*a22);
  a20=(a20+a10);
  a10=arg[0]? arg[0][3] : 0;
  a09=(a10*a16);
  a09=(a11*a09);
  a20=(a20+a09);
  a09=casadi_fabs(a01);
  a09=(a09*a18);
  a20=(a20+a09);
  a09=casadi_sign(a01);
  a08=(a01*a18);
  a09=(a09*a08);
  a20=(a20+a09);
  a09=46.;
  a08=(a09*a18);
  a20=(a20+a08);
  a08=(a17*a21);
  a08=(a00*a08);
  a20=(a20+a08);
  a20=(-a20);
  if (res[0]!=0) res[0][1]=a20;
  a20=(a11*a19);
  a08=(a20*a04);
  a19=(a19*a04);
  a19=(a00*a19);
  a08=(a08+a19);
  a19=(a00*a01);
  a07=(a19*a22);
  a08=(a08+a07);
  a01=(a01*a22);
  a01=(a11*a01);
  a08=(a08+a01);
  a01=casadi_fabs(a13);
  a01=(a01*a16);
  a08=(a08+a01);
  a01=casadi_sign(a13);
  a13=(a13*a16);
  a01=(a01*a13);
  a08=(a08+a01);
  a01=(a09*a16);
  a08=(a08+a01);
  a01=(a10*a18);
  a00=(a00*a01);
  a08=(a08+a00);
  a00=(a15*a21);
  a11=(a11*a00);
  a08=(a08+a11);
  a08=(-a08);
  if (res[0]!=0) res[0][2]=a08;
  a08=arg[1]? arg[1][6] : 0;
  a11=6.8000000000000005e-01;
  a00=(a15*a02);
  a00=(a11*a00);
  a00=(a08-a00);
  a01=-3.3199999999999998e+00;
  a13=(a01*a15);
  a13=(a13*a02);
  a00=(a00-a13);
  a13=-6.8000000000000005e-01;
  a07=(a17*a04);
  a07=(a13*a07);
  a00=(a00-a07);
  a07=3.3399999999999999e+00;
  a05=(a07*a17);
  a05=(a05*a04);
  a00=(a00-a05);
  a05=casadi_fabs(a10);
  a05=(a05*a22);
  a00=(a00-a05);
  a05=casadi_sign(a10);
  a23=(a10*a22);
  a05=(a05*a23);
  a00=(a00-a05);
  a05=(a09*a22);
  a00=(a00-a05);
  a12=(a12*a16);
  a00=(a00-a12);
  a14=(a14*a18);
  a00=(a00-a14);
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[0]? arg[0][6] : 0;
  a14=sin(a00);
  a12=arg[0]? arg[0][7] : 0;
  a05=cos(a12);
  a23=(a14/a05);
  a24=arg[1]? arg[1][8] : 0;
  a25=(a23*a24);
  a00=cos(a00);
  a26=arg[1]? arg[1][7] : 0;
  a27=(a00*a26);
  a25=(a25+a27);
  a27=tan(a12);
  a28=(a14*a27);
  a28=(a28*a08);
  a25=(a25+a28);
  a11=(a11*a10);
  a11=(a11*a02);
  a25=(a25-a11);
  a11=(a10*a02);
  a01=(a01*a11);
  a25=(a25-a01);
  a01=casadi_fabs(a15);
  a01=(a01*a04);
  a25=(a25-a01);
  a01=casadi_sign(a15);
  a11=(a15*a04);
  a01=(a01*a11);
  a25=(a25-a01);
  a01=(a09*a04);
  a25=(a25-a01);
  a01=3.3199999999999998e+00;
  a11=(a17*a22);
  a11=(a01*a11);
  a25=(a25-a11);
  a11=-3.3399999999999999e+00;
  a28=(a11*a17);
  a28=(a28*a22);
  a25=(a25-a28);
  a06=(a06*a16);
  a25=(a25-a06);
  a03=(a03*a21);
  a25=(a25-a03);
  if (res[0]!=0) res[0][4]=a25;
  a25=(a00/a05);
  a03=(a25*a24);
  a06=(a14*a26);
  a03=(a03-a06);
  a06=(a00*a27);
  a06=(a06*a08);
  a03=(a03+a06);
  a06=casadi_fabs(a17);
  a06=(a06*a02);
  a03=(a03-a06);
  a06=casadi_sign(a17);
  a16=(a17*a02);
  a06=(a06*a16);
  a03=(a03-a06);
  a09=(a09*a02);
  a03=(a03-a09);
  a13=(a13*a10);
  a13=(a13*a04);
  a03=(a03-a13);
  a10=(a10*a04);
  a07=(a07*a10);
  a03=(a03-a07);
  a01=(a01*a15);
  a01=(a01*a22);
  a03=(a03-a01);
  a22=(a15*a22);
  a11=(a11*a22);
  a03=(a03-a11);
  a20=(a20*a18);
  a03=(a03-a20);
  a19=(a19*a21);
  a03=(a03-a19);
  if (res[0]!=0) res[0][5]=a03;
  a03=(a15*a24);
  a19=(a03/a05);
  a19=(a00*a19);
  a24=(a17*a24);
  a20=(a24/a05);
  a20=(a14*a20);
  a19=(a19-a20);
  a20=(a17*a26);
  a20=(a00*a20);
  a19=(a19-a20);
  a26=(a15*a26);
  a26=(a14*a26);
  a19=(a19-a26);
  a17=(a17*a08);
  a26=(a27*a17);
  a26=(a14*a26);
  a19=(a19-a26);
  a15=(a15*a08);
  a27=(a27*a15);
  a27=(a00*a27);
  a19=(a19+a27);
  if (res[0]!=0) res[0][6]=a19;
  a12=sin(a12);
  a25=(a25/a05);
  a25=(a25*a24);
  a25=(a12*a25);
  a23=(a23/a05);
  a23=(a23*a03);
  a12=(a12*a23);
  a25=(a25+a12);
  a00=(a00*a17);
  a05=casadi_sq(a05);
  a00=(a00/a05);
  a25=(a25+a00);
  a14=(a14*a15);
  a14=(a14/a05);
  a25=(a25+a14);
  if (res[0]!=0) res[0][7]=a25;
  a25=0.;
  if (res[0]!=0) res[0][8]=a25;
  if (res[0]!=0) res[0][9]=a21;
  if (res[0]!=0) res[0][10]=a04;
  if (res[0]!=0) res[0][11]=a02;
  return 0;
}

CASADI_SYMBOL_EXPORT int auv_model_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int auv_model_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int auv_model_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void auv_model_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int auv_model_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void auv_model_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void auv_model_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void auv_model_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int auv_model_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int auv_model_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real auv_model_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* auv_model_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* auv_model_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* auv_model_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* auv_model_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int auv_model_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int auv_model_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
