/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) auv_model_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

static const casadi_int casadi_s0[3] = {9, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};

/* auv_model_expl_ode_fun:(i0[9],i1[3],i2[0])->(o0[9]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19;
  a00=3.3453634479321918e-02;
  a01=arg[1]? arg[1][0] : 0;
  a02=30.;
  a03=arg[0]? arg[0][2] : 0;
  a04=(a02*a03);
  a05=arg[0]? arg[0][4] : 0;
  a06=(a04*a05);
  a07=-30.;
  a08=arg[0]? arg[0][1] : 0;
  a09=(a07*a08);
  a10=arg[0]? arg[0][5] : 0;
  a11=(a09*a10);
  a06=(a06+a11);
  a01=(a01-a06);
  a06=23.;
  a11=arg[0]? arg[0][0] : 0;
  a06=(a06*a11);
  a12=casadi_fabs(a11);
  a12=(a12*a11);
  a06=(a06+a12);
  a01=(a01-a06);
  a00=(a00*a01);
  a06=6.0368975005218254e-05;
  a12=(a07*a03);
  a13=arg[0]? arg[0][3] : 0;
  a14=(a12*a13);
  a15=(a02*a11);
  a16=(a15*a10);
  a14=(a14+a16);
  a16=46.;
  a17=(a16*a08);
  a18=casadi_fabs(a08);
  a18=(a18*a08);
  a17=(a17+a18);
  a14=(a14+a17);
  a06=(a06*a14);
  a00=(a00-a06);
  a06=-1.1116270017027866e-07;
  a02=(a02*a08);
  a17=(a02*a13);
  a07=(a07*a11);
  a18=(a07*a05);
  a17=(a17+a18);
  a18=(a16*a03);
  a19=casadi_fabs(a03);
  a19=(a19*a03);
  a18=(a18+a19);
  a17=(a17+a18);
  a06=(a06*a17);
  a00=(a00-a06);
  a06=9.8084735444363873e-08;
  a04=(a04*a08);
  a09=(a09*a03);
  a04=(a04+a09);
  a09=-3.3399999999999999e+00;
  a09=(a09*a10);
  a09=(a09*a05);
  a04=(a04+a09);
  a09=3.3199999999999998e+00;
  a09=(a09*a05);
  a09=(a09*a10);
  a04=(a04+a09);
  a09=(a16*a13);
  a18=casadi_fabs(a13);
  a18=(a18*a13);
  a09=(a09+a18);
  a04=(a04+a09);
  a06=(a06*a04);
  a00=(a00-a06);
  a06=1.0920100546139184e-05;
  a09=arg[1]? arg[1][1] : 0;
  a12=(a12*a11);
  a15=(a15*a03);
  a12=(a12+a15);
  a15=3.3399999999999999e+00;
  a15=(a15*a10);
  a15=(a15*a13);
  a12=(a12+a15);
  a15=-6.8000000000000005e-01;
  a15=(a15*a13);
  a15=(a15*a10);
  a12=(a12+a15);
  a09=(a09-a12);
  a12=(a16*a05);
  a15=casadi_fabs(a05);
  a15=(a15*a05);
  a12=(a12+a15);
  a09=(a09-a12);
  a06=(a06*a09);
  a00=(a00+a06);
  a06=-6.0150572994295574e-03;
  a12=arg[1]? arg[1][2] : 0;
  a02=(a02*a11);
  a07=(a07*a08);
  a02=(a02+a07);
  a07=-3.3199999999999998e+00;
  a07=(a07*a05);
  a07=(a07*a13);
  a02=(a02+a07);
  a07=6.8000000000000005e-01;
  a07=(a07*a13);
  a07=(a07*a05);
  a02=(a02+a07);
  a12=(a12-a02);
  a16=(a16*a10);
  a02=casadi_fabs(a10);
  a02=(a02*a10);
  a16=(a16+a02);
  a12=(a12-a16);
  a06=(a06*a12);
  a00=(a00+a06);
  if (res[0]!=0) res[0][0]=a00;
  a00=6.0368975005218423e-05;
  a00=(a00*a01);
  a06=3.3484658136227786e-02;
  a06=(a06*a14);
  a00=(a00-a06);
  a06=-6.1658244361114702e-05;
  a06=(a06*a17);
  a00=(a00-a06);
  a06=5.4404333259807184e-05;
  a06=(a06*a04);
  a00=(a00-a06);
  a06=6.0570157695918683e-03;
  a06=(a06*a09);
  a00=(a00+a06);
  a06=-3.0184487502609172e-03;
  a06=(a06*a12);
  a00=(a00+a06);
  if (res[0]!=0) res[0][1]=a00;
  a00=-1.1116270017027936e-07;
  a00=(a00*a01);
  a06=-6.1658244361114783e-05;
  a06=(a06*a14);
  a00=(a00-a06);
  a06=3.3963490377380855e-02;
  a06=(a06*a17);
  a00=(a00-a06);
  a06=-2.9967785627100754e-02;
  a06=(a06*a04);
  a00=(a00-a06);
  a06=-3.0801331505514837e-03;
  a06=(a06*a09);
  a00=(a00+a06);
  a06=5.5581350085139543e-06;
  a06=(a06*a12);
  a00=(a00+a06);
  if (res[0]!=0) res[0][2]=a00;
  a00=9.8084735444364535e-08;
  a00=(a00*a01);
  a06=5.4404333259807062e-05;
  a06=(a06*a14);
  a00=(a00-a06);
  a06=-2.9967785627100469e-02;
  a06=(a06*a17);
  a00=(a00-a06);
  a06=1.4970303990827358e+00;
  a06=(a06*a04);
  a00=(a00-a06);
  a06=2.7177645446042520e-03;
  a06=(a06*a09);
  a00=(a00+a06);
  a06=-4.9042367722181902e-06;
  a06=(a06*a12);
  a00=(a00+a06);
  if (res[0]!=0) res[0][3]=a00;
  a00=1.0920100546139210e-05;
  a00=(a00*a01);
  a06=6.0570157695918657e-03;
  a06=(a06*a14);
  a00=(a00-a06);
  a06=-3.0801331505514781e-03;
  a06=(a06*a17);
  a00=(a00-a06);
  a06=2.7177645446042498e-03;
  a06=(a06*a04);
  a00=(a00-a06);
  a06=3.0257778596593993e-01;
  a06=(a06*a09);
  a00=(a00+a06);
  a06=-5.4600502730695923e-04;
  a16=(a06*a12);
  a00=(a00+a16);
  if (res[0]!=0) res[0][4]=a00;
  a00=-6.0150572994295635e-03;
  a00=(a00*a01);
  a01=-3.0184487502609133e-03;
  a01=(a01*a14);
  a00=(a00-a01);
  a01=5.5581350085139340e-06;
  a01=(a01*a17);
  a00=(a00-a01);
  a01=-4.9042367722181935e-06;
  a01=(a01*a04);
  a00=(a00-a01);
  a06=(a06*a09);
  a00=(a00+a06);
  a06=3.0075286497147785e-01;
  a06=(a06*a12);
  a00=(a00+a06);
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[0]? arg[0][6] : 0;
  a06=sin(a00);
  a12=arg[0]? arg[0][7] : 0;
  a09=tan(a12);
  a01=(a06*a09);
  a01=(a01*a05);
  a13=(a13+a01);
  a00=cos(a00);
  a09=(a00*a09);
  a09=(a09*a10);
  a13=(a13+a09);
  if (res[0]!=0) res[0][6]=a13;
  a13=(a00*a05);
  a09=(a06*a10);
  a13=(a13-a09);
  if (res[0]!=0) res[0][7]=a13;
  a12=cos(a12);
  a06=(a06/a12);
  a06=(a06*a05);
  a00=(a00/a12);
  a00=(a00*a10);
  a06=(a06+a00);
  if (res[0]!=0) res[0][8]=a06;
  return 0;
}

CASADI_SYMBOL_EXPORT int auv_model_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int auv_model_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int auv_model_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void auv_model_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int auv_model_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void auv_model_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void auv_model_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void auv_model_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int auv_model_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int auv_model_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real auv_model_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* auv_model_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* auv_model_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* auv_model_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* auv_model_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int auv_model_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int auv_model_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
