/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) auv_model_impl_dae_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {9, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[60] = 
  {9, 9, 0, 6, 12, 18, 25, 34,
  43, 46, 48, 48, 0, 1, 2, 3,
  4, 5, 0, 1, 2, 3, 4, 5,
  0, 1, 2, 3, 4, 5, 0, 1,
  2, 3, 4, 5, 6, 0, 1, 2,
  3, 4, 5, 6, 7, 8, 0, 1,
  2, 3, 4, 5, 6, 7, 8, 6,
  7, 8, 6, 8};
static const casadi_int casadi_s5[21] = 
  {9, 9, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 0, 1, 2, 3,
  4, 5, 6, 7, 8};
static const casadi_int casadi_s6[24] = 
  {9, 3, 0, 6, 12, 18, 0, 1,
  2, 3, 4, 5, 0, 1, 2, 3,
  4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s7[3] = {9, 0, 1};

/* auv_model_impl_dae_jac_x_xdot_u_z:(i0[9],i1[9],i2[3],i3[0],i4[],i5[0])->(o0[9x9,48nz],o1[9x9,9nz],o2[9x3,18nz],o3[9x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53;
  a00=3.3453634479321918e-02;
  a01=arg[0]? arg[0][0] : 0;
  a02=casadi_sign(a01);
  a02=(a01*a02);
  a03=23.;
  a04=casadi_fabs(a01);
  a03=(a03+a04);
  a02=(a02+a03);
  a03=(a00*a02);
  a04=6.0368975005218254e-05;
  a05=30.;
  a06=arg[0]? arg[0][5] : 0;
  a07=(a05*a06);
  a08=(a04*a07);
  a03=(a03+a08);
  a08=-1.1116270017027866e-07;
  a09=-30.;
  a10=arg[0]? arg[0][4] : 0;
  a11=(a09*a10);
  a12=(a08*a11);
  a03=(a03+a12);
  if (res[0]!=0) res[0][0]=a03;
  a03=6.0368975005218423e-05;
  a12=(a03*a02);
  a13=3.3484658136227786e-02;
  a14=(a13*a07);
  a12=(a12+a14);
  a14=-6.1658244361114702e-05;
  a15=(a14*a11);
  a12=(a12+a15);
  if (res[0]!=0) res[0][1]=a12;
  a12=-1.1116270017027936e-07;
  a15=(a12*a02);
  a16=-6.1658244361114783e-05;
  a17=(a16*a07);
  a15=(a15+a17);
  a17=3.3963490377380855e-02;
  a18=(a17*a11);
  a15=(a15+a18);
  if (res[0]!=0) res[0][2]=a15;
  a15=9.8084735444364535e-08;
  a18=(a15*a02);
  a19=5.4404333259807062e-05;
  a20=(a19*a07);
  a18=(a18+a20);
  a20=-2.9967785627100469e-02;
  a21=(a20*a11);
  a18=(a18+a21);
  if (res[0]!=0) res[0][3]=a18;
  a18=1.0920100546139210e-05;
  a21=(a18*a02);
  a22=6.0570157695918657e-03;
  a23=(a22*a07);
  a21=(a21+a23);
  a23=-3.0801331505514781e-03;
  a24=(a23*a11);
  a21=(a21+a24);
  if (res[0]!=0) res[0][4]=a21;
  a21=-6.0150572994295635e-03;
  a02=(a21*a02);
  a24=-3.0184487502609133e-03;
  a07=(a24*a07);
  a02=(a02+a07);
  a07=5.5581350085139340e-06;
  a11=(a07*a11);
  a02=(a02+a11);
  if (res[0]!=0) res[0][5]=a02;
  a02=(a09*a06);
  a11=(a00*a02);
  a25=arg[0]? arg[0][1] : 0;
  a26=casadi_sign(a25);
  a26=(a25*a26);
  a27=46.;
  a28=casadi_fabs(a25);
  a28=(a27+a28);
  a26=(a26+a28);
  a28=(a04*a26);
  a11=(a11+a28);
  a28=arg[0]? arg[0][3] : 0;
  a29=(a05*a28);
  a30=(a08*a29);
  a11=(a11+a30);
  if (res[0]!=0) res[0][6]=a11;
  a11=(a03*a02);
  a30=(a13*a26);
  a11=(a11+a30);
  a30=(a14*a29);
  a11=(a11+a30);
  if (res[0]!=0) res[0][7]=a11;
  a11=(a12*a02);
  a30=(a16*a26);
  a11=(a11+a30);
  a30=(a17*a29);
  a11=(a11+a30);
  if (res[0]!=0) res[0][8]=a11;
  a11=(a15*a02);
  a30=(a19*a26);
  a11=(a11+a30);
  a30=(a20*a29);
  a11=(a11+a30);
  if (res[0]!=0) res[0][9]=a11;
  a11=(a18*a02);
  a30=(a22*a26);
  a11=(a11+a30);
  a30=(a23*a29);
  a11=(a11+a30);
  if (res[0]!=0) res[0][10]=a11;
  a02=(a21*a02);
  a26=(a24*a26);
  a02=(a02+a26);
  a29=(a07*a29);
  a02=(a02+a29);
  if (res[0]!=0) res[0][11]=a02;
  a02=(a05*a10);
  a29=(a00*a02);
  a26=(a09*a28);
  a11=(a04*a26);
  a29=(a29+a11);
  a11=arg[0]? arg[0][2] : 0;
  a30=casadi_sign(a11);
  a30=(a11*a30);
  a31=casadi_fabs(a11);
  a31=(a27+a31);
  a30=(a30+a31);
  a31=(a08*a30);
  a29=(a29+a31);
  if (res[0]!=0) res[0][12]=a29;
  a29=(a03*a02);
  a31=(a13*a26);
  a29=(a29+a31);
  a31=(a14*a30);
  a29=(a29+a31);
  if (res[0]!=0) res[0][13]=a29;
  a29=(a12*a02);
  a31=(a16*a26);
  a29=(a29+a31);
  a31=(a17*a30);
  a29=(a29+a31);
  if (res[0]!=0) res[0][14]=a29;
  a29=(a15*a02);
  a31=(a19*a26);
  a29=(a29+a31);
  a31=(a20*a30);
  a29=(a29+a31);
  if (res[0]!=0) res[0][15]=a29;
  a29=(a18*a02);
  a31=(a22*a26);
  a29=(a29+a31);
  a31=(a23*a30);
  a29=(a29+a31);
  if (res[0]!=0) res[0][16]=a29;
  a02=(a21*a02);
  a26=(a24*a26);
  a02=(a02+a26);
  a30=(a07*a30);
  a02=(a02+a30);
  if (res[0]!=0) res[0][17]=a02;
  a02=(a09*a11);
  a30=(a04*a02);
  a26=(a05*a25);
  a29=(a08*a26);
  a30=(a30+a29);
  a29=9.8084735444363873e-08;
  a31=casadi_sign(a28);
  a31=(a28*a31);
  a32=casadi_fabs(a28);
  a32=(a27+a32);
  a31=(a31+a32);
  a32=(a29*a31);
  a30=(a30+a32);
  a32=1.0920100546139184e-05;
  a33=-3.3399999999999999e+00;
  a34=(a33*a06);
  a35=6.8000000000000005e-01;
  a36=(a35*a06);
  a34=(a34+a36);
  a36=(a32*a34);
  a30=(a30+a36);
  a36=-6.0150572994295574e-03;
  a37=3.3199999999999998e+00;
  a38=(a37*a10);
  a39=-6.8000000000000005e-01;
  a40=(a39*a10);
  a38=(a38+a40);
  a40=(a36*a38);
  a30=(a30+a40);
  if (res[0]!=0) res[0][18]=a30;
  a30=(a13*a02);
  a40=(a14*a26);
  a30=(a30+a40);
  a40=5.4404333259807184e-05;
  a41=(a40*a31);
  a30=(a30+a41);
  a41=6.0570157695918683e-03;
  a42=(a41*a34);
  a30=(a30+a42);
  a42=-3.0184487502609172e-03;
  a43=(a42*a38);
  a30=(a30+a43);
  if (res[0]!=0) res[0][19]=a30;
  a30=(a16*a02);
  a43=(a17*a26);
  a30=(a30+a43);
  a43=-2.9967785627100754e-02;
  a44=(a43*a31);
  a30=(a30+a44);
  a44=-3.0801331505514837e-03;
  a45=(a44*a34);
  a30=(a30+a45);
  a45=5.5581350085139543e-06;
  a46=(a45*a38);
  a30=(a30+a46);
  if (res[0]!=0) res[0][20]=a30;
  a30=(a19*a02);
  a46=(a20*a26);
  a30=(a30+a46);
  a46=1.4970303990827358e+00;
  a47=(a46*a31);
  a30=(a30+a47);
  a47=2.7177645446042520e-03;
  a48=(a47*a34);
  a30=(a30+a48);
  a48=-4.9042367722181902e-06;
  a49=(a48*a38);
  a30=(a30+a49);
  if (res[0]!=0) res[0][21]=a30;
  a30=(a22*a02);
  a49=(a23*a26);
  a30=(a30+a49);
  a49=2.7177645446042498e-03;
  a50=(a49*a31);
  a30=(a30+a50);
  a50=3.0257778596593993e-01;
  a51=(a50*a34);
  a30=(a30+a51);
  a51=-5.4600502730695923e-04;
  a52=(a51*a38);
  a30=(a30+a52);
  if (res[0]!=0) res[0][22]=a30;
  a02=(a24*a02);
  a26=(a07*a26);
  a02=(a02+a26);
  a26=-4.9042367722181935e-06;
  a31=(a26*a31);
  a02=(a02+a31);
  a34=(a51*a34);
  a02=(a02+a34);
  a34=3.0075286497147785e-01;
  a38=(a34*a38);
  a02=(a02+a38);
  if (res[0]!=0) res[0][23]=a02;
  a02=-1.;
  if (res[0]!=0) res[0][24]=a02;
  a11=(a05*a11);
  a02=(a00*a11);
  a38=(a09*a01);
  a08=(a08*a38);
  a02=(a02+a08);
  a08=3.3399999999999999e+00;
  a31=(a08*a06);
  a30=-3.3199999999999998e+00;
  a52=(a30*a06);
  a31=(a31+a52);
  a52=(a29*a31);
  a02=(a02+a52);
  a52=casadi_sign(a10);
  a52=(a10*a52);
  a53=casadi_fabs(a10);
  a53=(a27+a53);
  a52=(a52+a53);
  a53=(a32*a52);
  a02=(a02+a53);
  a37=(a37*a28);
  a39=(a39*a28);
  a37=(a37+a39);
  a39=(a36*a37);
  a02=(a02+a39);
  if (res[0]!=0) res[0][25]=a02;
  a02=(a03*a11);
  a14=(a14*a38);
  a02=(a02+a14);
  a14=(a40*a31);
  a02=(a02+a14);
  a14=(a41*a52);
  a02=(a02+a14);
  a14=(a42*a37);
  a02=(a02+a14);
  if (res[0]!=0) res[0][26]=a02;
  a02=(a12*a11);
  a17=(a17*a38);
  a02=(a02+a17);
  a17=(a43*a31);
  a02=(a02+a17);
  a17=(a44*a52);
  a02=(a02+a17);
  a17=(a45*a37);
  a02=(a02+a17);
  if (res[0]!=0) res[0][27]=a02;
  a02=(a15*a11);
  a20=(a20*a38);
  a02=(a02+a20);
  a20=(a46*a31);
  a02=(a02+a20);
  a20=(a47*a52);
  a02=(a02+a20);
  a20=(a48*a37);
  a02=(a02+a20);
  if (res[0]!=0) res[0][28]=a02;
  a02=(a18*a11);
  a23=(a23*a38);
  a02=(a02+a23);
  a23=(a49*a31);
  a02=(a02+a23);
  a23=(a50*a52);
  a02=(a02+a23);
  a23=(a51*a37);
  a02=(a02+a23);
  if (res[0]!=0) res[0][29]=a02;
  a11=(a21*a11);
  a07=(a07*a38);
  a11=(a11+a07);
  a31=(a26*a31);
  a11=(a11+a31);
  a52=(a51*a52);
  a11=(a11+a52);
  a37=(a34*a37);
  a11=(a11+a37);
  if (res[0]!=0) res[0][30]=a11;
  a11=arg[0]? arg[0][6] : 0;
  a37=sin(a11);
  a52=arg[0]? arg[0][7] : 0;
  a31=tan(a52);
  a07=(a37*a31);
  a07=(-a07);
  if (res[0]!=0) res[0][31]=a07;
  a11=cos(a11);
  a07=(-a11);
  if (res[0]!=0) res[0][32]=a07;
  a07=cos(a52);
  a38=(a37/a07);
  a02=(-a38);
  if (res[0]!=0) res[0][33]=a02;
  a09=(a09*a25);
  a00=(a00*a09);
  a05=(a05*a01);
  a04=(a04*a05);
  a00=(a00+a04);
  a08=(a08*a10);
  a30=(a30*a10);
  a08=(a08+a30);
  a29=(a29*a08);
  a00=(a00+a29);
  a33=(a33*a28);
  a35=(a35*a28);
  a33=(a33+a35);
  a32=(a32*a33);
  a00=(a00+a32);
  a32=casadi_sign(a06);
  a32=(a06*a32);
  a35=casadi_fabs(a06);
  a27=(a27+a35);
  a32=(a32+a27);
  a36=(a36*a32);
  a00=(a00+a36);
  if (res[0]!=0) res[0][34]=a00;
  a03=(a03*a09);
  a13=(a13*a05);
  a03=(a03+a13);
  a40=(a40*a08);
  a03=(a03+a40);
  a41=(a41*a33);
  a03=(a03+a41);
  a42=(a42*a32);
  a03=(a03+a42);
  if (res[0]!=0) res[0][35]=a03;
  a12=(a12*a09);
  a16=(a16*a05);
  a12=(a12+a16);
  a43=(a43*a08);
  a12=(a12+a43);
  a44=(a44*a33);
  a12=(a12+a44);
  a45=(a45*a32);
  a12=(a12+a45);
  if (res[0]!=0) res[0][36]=a12;
  a15=(a15*a09);
  a19=(a19*a05);
  a15=(a15+a19);
  a46=(a46*a08);
  a15=(a15+a46);
  a47=(a47*a33);
  a15=(a15+a47);
  a48=(a48*a32);
  a15=(a15+a48);
  if (res[0]!=0) res[0][37]=a15;
  a18=(a18*a09);
  a22=(a22*a05);
  a18=(a18+a22);
  a49=(a49*a08);
  a18=(a18+a49);
  a50=(a50*a33);
  a18=(a18+a50);
  a50=(a51*a32);
  a18=(a18+a50);
  if (res[0]!=0) res[0][38]=a18;
  a21=(a21*a09);
  a24=(a24*a05);
  a21=(a21+a24);
  a26=(a26*a08);
  a21=(a21+a26);
  a51=(a51*a33);
  a21=(a21+a51);
  a34=(a34*a32);
  a21=(a21+a34);
  if (res[0]!=0) res[0][39]=a21;
  a21=(a11*a31);
  a21=(-a21);
  if (res[0]!=0) res[0][40]=a21;
  if (res[0]!=0) res[0][41]=a37;
  a21=(a11/a07);
  a34=(-a21);
  if (res[0]!=0) res[0][42]=a34;
  a34=(a31*a11);
  a34=(a10*a34);
  a31=(a31*a37);
  a31=(a06*a31);
  a34=(a34-a31);
  a34=(-a34);
  if (res[0]!=0) res[0][43]=a34;
  a34=(a10*a37);
  a31=(a06*a11);
  a34=(a34+a31);
  if (res[0]!=0) res[0][44]=a34;
  a34=(a10*a21);
  a31=(a06*a38);
  a34=(a34-a31);
  a34=(-a34);
  if (res[0]!=0) res[0][45]=a34;
  a34=casadi_sq(a07);
  a37=(a37/a34);
  a37=(a10*a37);
  a11=(a11/a34);
  a11=(a06*a11);
  a37=(a37+a11);
  a37=(-a37);
  if (res[0]!=0) res[0][46]=a37;
  a38=(a38/a07);
  a52=sin(a52);
  a38=(a38*a52);
  a10=(a10*a38);
  a21=(a21/a07);
  a21=(a21*a52);
  a06=(a06*a21);
  a10=(a10+a06);
  a10=(-a10);
  if (res[0]!=0) res[0][47]=a10;
  a10=1.;
  if (res[1]!=0) res[1][0]=a10;
  if (res[1]!=0) res[1][1]=a10;
  if (res[1]!=0) res[1][2]=a10;
  if (res[1]!=0) res[1][3]=a10;
  if (res[1]!=0) res[1][4]=a10;
  if (res[1]!=0) res[1][5]=a10;
  if (res[1]!=0) res[1][6]=a10;
  if (res[1]!=0) res[1][7]=a10;
  if (res[1]!=0) res[1][8]=a10;
  a10=-3.3453634479321918e-02;
  if (res[2]!=0) res[2][0]=a10;
  a10=-6.0368975005218423e-05;
  if (res[2]!=0) res[2][1]=a10;
  a10=1.1116270017027936e-07;
  if (res[2]!=0) res[2][2]=a10;
  a10=-9.8084735444364535e-08;
  if (res[2]!=0) res[2][3]=a10;
  a10=-1.0920100546139210e-05;
  if (res[2]!=0) res[2][4]=a10;
  a10=6.0150572994295635e-03;
  if (res[2]!=0) res[2][5]=a10;
  a10=-1.0920100546139184e-05;
  if (res[2]!=0) res[2][6]=a10;
  a10=-6.0570157695918683e-03;
  if (res[2]!=0) res[2][7]=a10;
  a10=3.0801331505514837e-03;
  if (res[2]!=0) res[2][8]=a10;
  a10=-2.7177645446042520e-03;
  if (res[2]!=0) res[2][9]=a10;
  a10=-3.0257778596593993e-01;
  if (res[2]!=0) res[2][10]=a10;
  a10=5.4600502730695923e-04;
  if (res[2]!=0) res[2][11]=a10;
  a06=6.0150572994295574e-03;
  if (res[2]!=0) res[2][12]=a06;
  a06=3.0184487502609172e-03;
  if (res[2]!=0) res[2][13]=a06;
  a06=-5.5581350085139543e-06;
  if (res[2]!=0) res[2][14]=a06;
  a06=4.9042367722181902e-06;
  if (res[2]!=0) res[2][15]=a06;
  if (res[2]!=0) res[2][16]=a10;
  a10=-3.0075286497147785e-01;
  if (res[2]!=0) res[2][17]=a10;
  return 0;
}

CASADI_SYMBOL_EXPORT int auv_model_impl_dae_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int auv_model_impl_dae_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int auv_model_impl_dae_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void auv_model_impl_dae_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int auv_model_impl_dae_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void auv_model_impl_dae_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void auv_model_impl_dae_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void auv_model_impl_dae_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int auv_model_impl_dae_jac_x_xdot_u_z_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int auv_model_impl_dae_jac_x_xdot_u_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real auv_model_impl_dae_jac_x_xdot_u_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* auv_model_impl_dae_jac_x_xdot_u_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* auv_model_impl_dae_jac_x_xdot_u_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* auv_model_impl_dae_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    case 5: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* auv_model_impl_dae_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int auv_model_impl_dae_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int auv_model_impl_dae_jac_x_xdot_u_z_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
