/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) auv_model_impl_dae_fun_jac_x_xdot_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {9, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[60] = 
  {9, 9, 0, 6, 12, 18, 25, 34,
  43, 46, 48, 48, 0, 1, 2, 3,
  4, 5, 0, 1, 2, 3, 4, 5,
  0, 1, 2, 3, 4, 5, 0, 1,
  2, 3, 4, 5, 6, 0, 1, 2,
  3, 4, 5, 6, 7, 8, 0, 1,
  2, 3, 4, 5, 6, 7, 8, 6,
  7, 8, 6, 8};
static const casadi_int casadi_s5[21] = 
  {9, 9, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 0, 1, 2, 3,
  4, 5, 6, 7, 8};
static const casadi_int casadi_s6[3] = {9, 0, 1};

/* auv_model_impl_dae_fun_jac_x_xdot_z:(i0[9],i1[9],i2[3],i3[0],i4[],i5[0])->(o0[9],o1[9x9,48nz],o2[9x9,9nz],o3[9x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59;
  casadi_real a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a70, a71;
  casadi_real a72, a73, a74, a75, a76, a77, a78;
  a00=arg[1]? arg[1][0] : 0;
  a01=3.3453634479321918e-02;
  a02=arg[2]? arg[2][0] : 0;
  a03=-30.;
  a04=arg[0]? arg[0][5] : 0;
  a05=(a03*a04);
  a06=arg[0]? arg[0][1] : 0;
  a07=(a05*a06);
  a08=30.;
  a09=arg[0]? arg[0][4] : 0;
  a10=(a08*a09);
  a11=arg[0]? arg[0][2] : 0;
  a12=(a10*a11);
  a07=(a07+a12);
  a02=(a02-a07);
  a07=23.;
  a12=arg[0]? arg[0][0] : 0;
  a13=casadi_fabs(a12);
  a07=(a07+a13);
  a13=(a07*a12);
  a02=(a02-a13);
  a13=(a01*a02);
  a14=6.0368975005218254e-05;
  a15=(a08*a04);
  a16=(a15*a12);
  a17=arg[0]? arg[0][3] : 0;
  a18=(a03*a17);
  a19=(a18*a11);
  a16=(a16+a19);
  a19=46.;
  a20=casadi_fabs(a06);
  a20=(a19+a20);
  a21=(a20*a06);
  a16=(a16+a21);
  a21=(a14*a16);
  a13=(a13-a21);
  a21=-1.1116270017027866e-07;
  a22=(a03*a09);
  a23=(a22*a12);
  a24=(a08*a17);
  a25=(a24*a06);
  a23=(a23+a25);
  a25=casadi_fabs(a11);
  a25=(a19+a25);
  a26=(a25*a11);
  a23=(a23+a26);
  a26=(a21*a23);
  a13=(a13-a26);
  a26=9.8084735444363873e-08;
  a27=3.3399999999999999e+00;
  a28=(a27*a04);
  a29=(a28*a09);
  a30=-3.3199999999999998e+00;
  a31=(a30*a09);
  a32=(a31*a04);
  a29=(a29+a32);
  a32=casadi_fabs(a17);
  a32=(a19+a32);
  a33=(a32*a17);
  a29=(a29+a33);
  a33=(a26*a29);
  a13=(a13-a33);
  a33=1.0920100546139184e-05;
  a34=arg[2]? arg[2][1] : 0;
  a35=-3.3399999999999999e+00;
  a36=(a35*a04);
  a37=(a36*a17);
  a38=6.8000000000000005e-01;
  a39=(a38*a17);
  a40=(a39*a04);
  a37=(a37+a40);
  a34=(a34-a37);
  a37=casadi_fabs(a09);
  a37=(a19+a37);
  a40=(a37*a09);
  a34=(a34-a40);
  a40=(a33*a34);
  a13=(a13+a40);
  a40=-6.0150572994295574e-03;
  a41=arg[2]? arg[2][2] : 0;
  a42=3.3199999999999998e+00;
  a43=(a42*a09);
  a44=(a43*a17);
  a45=-6.8000000000000005e-01;
  a46=(a45*a17);
  a47=(a46*a09);
  a44=(a44+a47);
  a41=(a41-a44);
  a44=casadi_fabs(a04);
  a19=(a19+a44);
  a44=(a19*a04);
  a41=(a41-a44);
  a44=(a40*a41);
  a13=(a13+a44);
  a00=(a00-a13);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[1]? arg[1][1] : 0;
  a13=6.0368975005218423e-05;
  a44=(a13*a02);
  a47=3.3484658136227786e-02;
  a48=(a47*a16);
  a44=(a44-a48);
  a48=-6.1658244361114702e-05;
  a49=(a48*a23);
  a44=(a44-a49);
  a49=5.4404333259807184e-05;
  a50=(a49*a29);
  a44=(a44-a50);
  a50=6.0570157695918683e-03;
  a51=(a50*a34);
  a44=(a44+a51);
  a51=-3.0184487502609172e-03;
  a52=(a51*a41);
  a44=(a44+a52);
  a00=(a00-a44);
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[1]? arg[1][2] : 0;
  a44=-1.1116270017027936e-07;
  a52=(a44*a02);
  a53=-6.1658244361114783e-05;
  a54=(a53*a16);
  a52=(a52-a54);
  a54=3.3963490377380855e-02;
  a55=(a54*a23);
  a52=(a52-a55);
  a55=-2.9967785627100754e-02;
  a56=(a55*a29);
  a52=(a52-a56);
  a56=-3.0801331505514837e-03;
  a57=(a56*a34);
  a52=(a52+a57);
  a57=5.5581350085139543e-06;
  a58=(a57*a41);
  a52=(a52+a58);
  a00=(a00-a52);
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[1]? arg[1][3] : 0;
  a52=9.8084735444364535e-08;
  a58=(a52*a02);
  a59=5.4404333259807062e-05;
  a60=(a59*a16);
  a58=(a58-a60);
  a60=-2.9967785627100469e-02;
  a61=(a60*a23);
  a58=(a58-a61);
  a61=1.4970303990827358e+00;
  a62=(a61*a29);
  a58=(a58-a62);
  a62=2.7177645446042520e-03;
  a63=(a62*a34);
  a58=(a58+a63);
  a63=-4.9042367722181902e-06;
  a64=(a63*a41);
  a58=(a58+a64);
  a00=(a00-a58);
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[1]? arg[1][4] : 0;
  a58=1.0920100546139210e-05;
  a64=(a58*a02);
  a65=6.0570157695918657e-03;
  a66=(a65*a16);
  a64=(a64-a66);
  a66=-3.0801331505514781e-03;
  a67=(a66*a23);
  a64=(a64-a67);
  a67=2.7177645446042498e-03;
  a68=(a67*a29);
  a64=(a64-a68);
  a68=3.0257778596593993e-01;
  a69=(a68*a34);
  a64=(a64+a69);
  a69=-5.4600502730695923e-04;
  a70=(a69*a41);
  a64=(a64+a70);
  a00=(a00-a64);
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[1]? arg[1][5] : 0;
  a64=-6.0150572994295635e-03;
  a02=(a64*a02);
  a70=-3.0184487502609133e-03;
  a16=(a70*a16);
  a02=(a02-a16);
  a16=5.5581350085139340e-06;
  a23=(a16*a23);
  a02=(a02-a23);
  a23=-4.9042367722181935e-06;
  a29=(a23*a29);
  a02=(a02-a29);
  a34=(a69*a34);
  a02=(a02+a34);
  a34=3.0075286497147785e-01;
  a41=(a34*a41);
  a02=(a02+a41);
  a00=(a00-a02);
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[1]? arg[1][6] : 0;
  a02=arg[0]? arg[0][6] : 0;
  a41=sin(a02);
  a29=arg[0]? arg[0][7] : 0;
  a71=tan(a29);
  a72=(a41*a71);
  a73=(a72*a09);
  a73=(a17+a73);
  a02=cos(a02);
  a74=(a02*a71);
  a75=(a74*a04);
  a73=(a73+a75);
  a00=(a00-a73);
  if (res[0]!=0) res[0][6]=a00;
  a00=arg[1]? arg[1][7] : 0;
  a73=(a02*a09);
  a75=(a41*a04);
  a73=(a73-a75);
  a00=(a00-a73);
  if (res[0]!=0) res[0][7]=a00;
  a00=arg[1]? arg[1][8] : 0;
  a73=cos(a29);
  a75=(a41/a73);
  a76=(a75*a09);
  a77=(a02/a73);
  a78=(a77*a04);
  a76=(a76+a78);
  a00=(a00-a76);
  if (res[0]!=0) res[0][8]=a00;
  a00=casadi_sign(a12);
  a00=(a12*a00);
  a00=(a00+a07);
  a07=(a01*a00);
  a76=(a14*a15);
  a07=(a07+a76);
  a76=(a21*a22);
  a07=(a07+a76);
  if (res[1]!=0) res[1][0]=a07;
  a07=(a13*a00);
  a76=(a47*a15);
  a07=(a07+a76);
  a76=(a48*a22);
  a07=(a07+a76);
  if (res[1]!=0) res[1][1]=a07;
  a07=(a44*a00);
  a76=(a53*a15);
  a07=(a07+a76);
  a76=(a54*a22);
  a07=(a07+a76);
  if (res[1]!=0) res[1][2]=a07;
  a07=(a52*a00);
  a76=(a59*a15);
  a07=(a07+a76);
  a76=(a60*a22);
  a07=(a07+a76);
  if (res[1]!=0) res[1][3]=a07;
  a07=(a58*a00);
  a76=(a65*a15);
  a07=(a07+a76);
  a76=(a66*a22);
  a07=(a07+a76);
  if (res[1]!=0) res[1][4]=a07;
  a00=(a64*a00);
  a15=(a70*a15);
  a00=(a00+a15);
  a22=(a16*a22);
  a00=(a00+a22);
  if (res[1]!=0) res[1][5]=a00;
  a00=(a01*a05);
  a22=casadi_sign(a06);
  a22=(a06*a22);
  a22=(a22+a20);
  a20=(a14*a22);
  a00=(a00+a20);
  a20=(a21*a24);
  a00=(a00+a20);
  if (res[1]!=0) res[1][6]=a00;
  a00=(a13*a05);
  a20=(a47*a22);
  a00=(a00+a20);
  a20=(a48*a24);
  a00=(a00+a20);
  if (res[1]!=0) res[1][7]=a00;
  a00=(a44*a05);
  a20=(a53*a22);
  a00=(a00+a20);
  a20=(a54*a24);
  a00=(a00+a20);
  if (res[1]!=0) res[1][8]=a00;
  a00=(a52*a05);
  a20=(a59*a22);
  a00=(a00+a20);
  a20=(a60*a24);
  a00=(a00+a20);
  if (res[1]!=0) res[1][9]=a00;
  a00=(a58*a05);
  a20=(a65*a22);
  a00=(a00+a20);
  a20=(a66*a24);
  a00=(a00+a20);
  if (res[1]!=0) res[1][10]=a00;
  a05=(a64*a05);
  a22=(a70*a22);
  a05=(a05+a22);
  a24=(a16*a24);
  a05=(a05+a24);
  if (res[1]!=0) res[1][11]=a05;
  a05=(a01*a10);
  a24=(a14*a18);
  a05=(a05+a24);
  a24=casadi_sign(a11);
  a24=(a11*a24);
  a24=(a24+a25);
  a25=(a21*a24);
  a05=(a05+a25);
  if (res[1]!=0) res[1][12]=a05;
  a05=(a13*a10);
  a25=(a47*a18);
  a05=(a05+a25);
  a25=(a48*a24);
  a05=(a05+a25);
  if (res[1]!=0) res[1][13]=a05;
  a05=(a44*a10);
  a25=(a53*a18);
  a05=(a05+a25);
  a25=(a54*a24);
  a05=(a05+a25);
  if (res[1]!=0) res[1][14]=a05;
  a05=(a52*a10);
  a25=(a59*a18);
  a05=(a05+a25);
  a25=(a60*a24);
  a05=(a05+a25);
  if (res[1]!=0) res[1][15]=a05;
  a05=(a58*a10);
  a25=(a65*a18);
  a05=(a05+a25);
  a25=(a66*a24);
  a05=(a05+a25);
  if (res[1]!=0) res[1][16]=a05;
  a10=(a64*a10);
  a18=(a70*a18);
  a10=(a10+a18);
  a24=(a16*a24);
  a10=(a10+a24);
  if (res[1]!=0) res[1][17]=a10;
  a10=(a03*a11);
  a24=(a14*a10);
  a18=(a08*a06);
  a05=(a21*a18);
  a24=(a24+a05);
  a05=casadi_sign(a17);
  a05=(a17*a05);
  a05=(a05+a32);
  a32=(a26*a05);
  a24=(a24+a32);
  a38=(a38*a04);
  a36=(a36+a38);
  a38=(a33*a36);
  a24=(a24+a38);
  a45=(a45*a09);
  a43=(a43+a45);
  a45=(a40*a43);
  a24=(a24+a45);
  if (res[1]!=0) res[1][18]=a24;
  a24=(a47*a10);
  a45=(a48*a18);
  a24=(a24+a45);
  a45=(a49*a05);
  a24=(a24+a45);
  a45=(a50*a36);
  a24=(a24+a45);
  a45=(a51*a43);
  a24=(a24+a45);
  if (res[1]!=0) res[1][19]=a24;
  a24=(a53*a10);
  a45=(a54*a18);
  a24=(a24+a45);
  a45=(a55*a05);
  a24=(a24+a45);
  a45=(a56*a36);
  a24=(a24+a45);
  a45=(a57*a43);
  a24=(a24+a45);
  if (res[1]!=0) res[1][20]=a24;
  a24=(a59*a10);
  a45=(a60*a18);
  a24=(a24+a45);
  a45=(a61*a05);
  a24=(a24+a45);
  a45=(a62*a36);
  a24=(a24+a45);
  a45=(a63*a43);
  a24=(a24+a45);
  if (res[1]!=0) res[1][21]=a24;
  a24=(a65*a10);
  a45=(a66*a18);
  a24=(a24+a45);
  a45=(a67*a05);
  a24=(a24+a45);
  a45=(a68*a36);
  a24=(a24+a45);
  a45=(a69*a43);
  a24=(a24+a45);
  if (res[1]!=0) res[1][22]=a24;
  a10=(a70*a10);
  a18=(a16*a18);
  a10=(a10+a18);
  a05=(a23*a05);
  a10=(a10+a05);
  a36=(a69*a36);
  a10=(a10+a36);
  a43=(a34*a43);
  a10=(a10+a43);
  if (res[1]!=0) res[1][23]=a10;
  a10=-1.;
  if (res[1]!=0) res[1][24]=a10;
  a11=(a08*a11);
  a10=(a01*a11);
  a43=(a03*a12);
  a21=(a21*a43);
  a10=(a10+a21);
  a30=(a30*a04);
  a28=(a28+a30);
  a30=(a26*a28);
  a10=(a10+a30);
  a30=casadi_sign(a09);
  a30=(a09*a30);
  a30=(a30+a37);
  a37=(a33*a30);
  a10=(a10+a37);
  a42=(a42*a17);
  a42=(a42+a46);
  a46=(a40*a42);
  a10=(a10+a46);
  if (res[1]!=0) res[1][25]=a10;
  a10=(a13*a11);
  a48=(a48*a43);
  a10=(a10+a48);
  a48=(a49*a28);
  a10=(a10+a48);
  a48=(a50*a30);
  a10=(a10+a48);
  a48=(a51*a42);
  a10=(a10+a48);
  if (res[1]!=0) res[1][26]=a10;
  a10=(a44*a11);
  a54=(a54*a43);
  a10=(a10+a54);
  a54=(a55*a28);
  a10=(a10+a54);
  a54=(a56*a30);
  a10=(a10+a54);
  a54=(a57*a42);
  a10=(a10+a54);
  if (res[1]!=0) res[1][27]=a10;
  a10=(a52*a11);
  a60=(a60*a43);
  a10=(a10+a60);
  a60=(a61*a28);
  a10=(a10+a60);
  a60=(a62*a30);
  a10=(a10+a60);
  a60=(a63*a42);
  a10=(a10+a60);
  if (res[1]!=0) res[1][28]=a10;
  a10=(a58*a11);
  a66=(a66*a43);
  a10=(a10+a66);
  a66=(a67*a28);
  a10=(a10+a66);
  a66=(a68*a30);
  a10=(a10+a66);
  a66=(a69*a42);
  a10=(a10+a66);
  if (res[1]!=0) res[1][29]=a10;
  a11=(a64*a11);
  a16=(a16*a43);
  a11=(a11+a16);
  a28=(a23*a28);
  a11=(a11+a28);
  a30=(a69*a30);
  a11=(a11+a30);
  a42=(a34*a42);
  a11=(a11+a42);
  if (res[1]!=0) res[1][30]=a11;
  a72=(-a72);
  if (res[1]!=0) res[1][31]=a72;
  a72=(-a02);
  if (res[1]!=0) res[1][32]=a72;
  a72=(-a75);
  if (res[1]!=0) res[1][33]=a72;
  a03=(a03*a06);
  a01=(a01*a03);
  a08=(a08*a12);
  a14=(a14*a08);
  a01=(a01+a14);
  a27=(a27*a09);
  a27=(a27+a31);
  a26=(a26*a27);
  a01=(a01+a26);
  a35=(a35*a17);
  a35=(a35+a39);
  a33=(a33*a35);
  a01=(a01+a33);
  a33=casadi_sign(a04);
  a33=(a04*a33);
  a33=(a33+a19);
  a40=(a40*a33);
  a01=(a01+a40);
  if (res[1]!=0) res[1][34]=a01;
  a13=(a13*a03);
  a47=(a47*a08);
  a13=(a13+a47);
  a49=(a49*a27);
  a13=(a13+a49);
  a50=(a50*a35);
  a13=(a13+a50);
  a51=(a51*a33);
  a13=(a13+a51);
  if (res[1]!=0) res[1][35]=a13;
  a44=(a44*a03);
  a53=(a53*a08);
  a44=(a44+a53);
  a55=(a55*a27);
  a44=(a44+a55);
  a56=(a56*a35);
  a44=(a44+a56);
  a57=(a57*a33);
  a44=(a44+a57);
  if (res[1]!=0) res[1][36]=a44;
  a52=(a52*a03);
  a59=(a59*a08);
  a52=(a52+a59);
  a61=(a61*a27);
  a52=(a52+a61);
  a62=(a62*a35);
  a52=(a52+a62);
  a63=(a63*a33);
  a52=(a52+a63);
  if (res[1]!=0) res[1][37]=a52;
  a58=(a58*a03);
  a65=(a65*a08);
  a58=(a58+a65);
  a67=(a67*a27);
  a58=(a58+a67);
  a68=(a68*a35);
  a58=(a58+a68);
  a68=(a69*a33);
  a58=(a58+a68);
  if (res[1]!=0) res[1][38]=a58;
  a64=(a64*a03);
  a70=(a70*a08);
  a64=(a64+a70);
  a23=(a23*a27);
  a64=(a64+a23);
  a69=(a69*a35);
  a64=(a64+a69);
  a34=(a34*a33);
  a64=(a64+a34);
  if (res[1]!=0) res[1][39]=a64;
  a74=(-a74);
  if (res[1]!=0) res[1][40]=a74;
  if (res[1]!=0) res[1][41]=a41;
  a74=(-a77);
  if (res[1]!=0) res[1][42]=a74;
  a74=(a71*a02);
  a74=(a09*a74);
  a71=(a71*a41);
  a71=(a04*a71);
  a74=(a74-a71);
  a74=(-a74);
  if (res[1]!=0) res[1][43]=a74;
  a74=(a09*a41);
  a71=(a04*a02);
  a74=(a74+a71);
  if (res[1]!=0) res[1][44]=a74;
  a74=(a09*a77);
  a71=(a04*a75);
  a74=(a74-a71);
  a74=(-a74);
  if (res[1]!=0) res[1][45]=a74;
  a74=casadi_sq(a73);
  a41=(a41/a74);
  a41=(a09*a41);
  a02=(a02/a74);
  a02=(a04*a02);
  a41=(a41+a02);
  a41=(-a41);
  if (res[1]!=0) res[1][46]=a41;
  a75=(a75/a73);
  a29=sin(a29);
  a75=(a75*a29);
  a09=(a09*a75);
  a77=(a77/a73);
  a77=(a77*a29);
  a04=(a04*a77);
  a09=(a09+a04);
  a09=(-a09);
  if (res[1]!=0) res[1][47]=a09;
  a09=1.;
  if (res[2]!=0) res[2][0]=a09;
  if (res[2]!=0) res[2][1]=a09;
  if (res[2]!=0) res[2][2]=a09;
  if (res[2]!=0) res[2][3]=a09;
  if (res[2]!=0) res[2][4]=a09;
  if (res[2]!=0) res[2][5]=a09;
  if (res[2]!=0) res[2][6]=a09;
  if (res[2]!=0) res[2][7]=a09;
  if (res[2]!=0) res[2][8]=a09;
  return 0;
}

CASADI_SYMBOL_EXPORT int auv_model_impl_dae_fun_jac_x_xdot_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int auv_model_impl_dae_fun_jac_x_xdot_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int auv_model_impl_dae_fun_jac_x_xdot_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void auv_model_impl_dae_fun_jac_x_xdot_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int auv_model_impl_dae_fun_jac_x_xdot_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void auv_model_impl_dae_fun_jac_x_xdot_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void auv_model_impl_dae_fun_jac_x_xdot_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void auv_model_impl_dae_fun_jac_x_xdot_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int auv_model_impl_dae_fun_jac_x_xdot_z_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int auv_model_impl_dae_fun_jac_x_xdot_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real auv_model_impl_dae_fun_jac_x_xdot_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* auv_model_impl_dae_fun_jac_x_xdot_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* auv_model_impl_dae_fun_jac_x_xdot_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* auv_model_impl_dae_fun_jac_x_xdot_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    case 5: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* auv_model_impl_dae_fun_jac_x_xdot_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int auv_model_impl_dae_fun_jac_x_xdot_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int auv_model_impl_dae_fun_jac_x_xdot_z_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
