/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) auv_model_impl_dae_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

static const casadi_int casadi_s0[3] = {9, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};

/* auv_model_impl_dae_fun:(i0[9],i1[9],i2[3],i3[0],i4[],i5[0])->(o0[9]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14;
  a00=arg[1]? arg[1][0] : 0;
  a01=3.3453634479321918e-02;
  a02=arg[2]? arg[2][0] : 0;
  a03=-30.;
  a04=arg[0]? arg[0][5] : 0;
  a05=(a03*a04);
  a06=arg[0]? arg[0][1] : 0;
  a05=(a05*a06);
  a07=30.;
  a08=arg[0]? arg[0][4] : 0;
  a09=(a07*a08);
  a10=arg[0]? arg[0][2] : 0;
  a09=(a09*a10);
  a05=(a05+a09);
  a02=(a02-a05);
  a05=23.;
  a09=arg[0]? arg[0][0] : 0;
  a11=casadi_fabs(a09);
  a05=(a05+a11);
  a05=(a05*a09);
  a02=(a02-a05);
  a01=(a01*a02);
  a05=6.0368975005218254e-05;
  a11=(a07*a04);
  a11=(a11*a09);
  a12=arg[0]? arg[0][3] : 0;
  a13=(a03*a12);
  a13=(a13*a10);
  a11=(a11+a13);
  a13=46.;
  a14=casadi_fabs(a06);
  a14=(a13+a14);
  a14=(a14*a06);
  a11=(a11+a14);
  a05=(a05*a11);
  a01=(a01-a05);
  a05=-1.1116270017027866e-07;
  a03=(a03*a08);
  a03=(a03*a09);
  a07=(a07*a12);
  a07=(a07*a06);
  a03=(a03+a07);
  a07=casadi_fabs(a10);
  a07=(a13+a07);
  a07=(a07*a10);
  a03=(a03+a07);
  a05=(a05*a03);
  a01=(a01-a05);
  a05=9.8084735444363873e-08;
  a07=3.3399999999999999e+00;
  a07=(a07*a04);
  a07=(a07*a08);
  a10=-3.3199999999999998e+00;
  a10=(a10*a08);
  a10=(a10*a04);
  a07=(a07+a10);
  a10=casadi_fabs(a12);
  a10=(a13+a10);
  a10=(a10*a12);
  a07=(a07+a10);
  a05=(a05*a07);
  a01=(a01-a05);
  a05=1.0920100546139184e-05;
  a10=arg[2]? arg[2][1] : 0;
  a06=-3.3399999999999999e+00;
  a06=(a06*a04);
  a06=(a06*a12);
  a09=6.8000000000000005e-01;
  a09=(a09*a12);
  a09=(a09*a04);
  a06=(a06+a09);
  a10=(a10-a06);
  a06=casadi_fabs(a08);
  a06=(a13+a06);
  a06=(a06*a08);
  a10=(a10-a06);
  a05=(a05*a10);
  a01=(a01+a05);
  a05=-6.0150572994295574e-03;
  a06=arg[2]? arg[2][2] : 0;
  a09=3.3199999999999998e+00;
  a09=(a09*a08);
  a09=(a09*a12);
  a14=-6.8000000000000005e-01;
  a14=(a14*a12);
  a14=(a14*a08);
  a09=(a09+a14);
  a06=(a06-a09);
  a09=casadi_fabs(a04);
  a13=(a13+a09);
  a13=(a13*a04);
  a06=(a06-a13);
  a05=(a05*a06);
  a01=(a01+a05);
  a00=(a00-a01);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[1]? arg[1][1] : 0;
  a01=6.0368975005218423e-05;
  a01=(a01*a02);
  a05=3.3484658136227786e-02;
  a05=(a05*a11);
  a01=(a01-a05);
  a05=-6.1658244361114702e-05;
  a05=(a05*a03);
  a01=(a01-a05);
  a05=5.4404333259807184e-05;
  a05=(a05*a07);
  a01=(a01-a05);
  a05=6.0570157695918683e-03;
  a05=(a05*a10);
  a01=(a01+a05);
  a05=-3.0184487502609172e-03;
  a05=(a05*a06);
  a01=(a01+a05);
  a00=(a00-a01);
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[1]? arg[1][2] : 0;
  a01=-1.1116270017027936e-07;
  a01=(a01*a02);
  a05=-6.1658244361114783e-05;
  a05=(a05*a11);
  a01=(a01-a05);
  a05=3.3963490377380855e-02;
  a05=(a05*a03);
  a01=(a01-a05);
  a05=-2.9967785627100754e-02;
  a05=(a05*a07);
  a01=(a01-a05);
  a05=-3.0801331505514837e-03;
  a05=(a05*a10);
  a01=(a01+a05);
  a05=5.5581350085139543e-06;
  a05=(a05*a06);
  a01=(a01+a05);
  a00=(a00-a01);
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[1]? arg[1][3] : 0;
  a01=9.8084735444364535e-08;
  a01=(a01*a02);
  a05=5.4404333259807062e-05;
  a05=(a05*a11);
  a01=(a01-a05);
  a05=-2.9967785627100469e-02;
  a05=(a05*a03);
  a01=(a01-a05);
  a05=1.4970303990827358e+00;
  a05=(a05*a07);
  a01=(a01-a05);
  a05=2.7177645446042520e-03;
  a05=(a05*a10);
  a01=(a01+a05);
  a05=-4.9042367722181902e-06;
  a05=(a05*a06);
  a01=(a01+a05);
  a00=(a00-a01);
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[1]? arg[1][4] : 0;
  a01=1.0920100546139210e-05;
  a01=(a01*a02);
  a05=6.0570157695918657e-03;
  a05=(a05*a11);
  a01=(a01-a05);
  a05=-3.0801331505514781e-03;
  a05=(a05*a03);
  a01=(a01-a05);
  a05=2.7177645446042498e-03;
  a05=(a05*a07);
  a01=(a01-a05);
  a05=3.0257778596593993e-01;
  a05=(a05*a10);
  a01=(a01+a05);
  a05=-5.4600502730695923e-04;
  a13=(a05*a06);
  a01=(a01+a13);
  a00=(a00-a01);
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[1]? arg[1][5] : 0;
  a01=-6.0150572994295635e-03;
  a01=(a01*a02);
  a02=-3.0184487502609133e-03;
  a02=(a02*a11);
  a01=(a01-a02);
  a02=5.5581350085139340e-06;
  a02=(a02*a03);
  a01=(a01-a02);
  a02=-4.9042367722181935e-06;
  a02=(a02*a07);
  a01=(a01-a02);
  a05=(a05*a10);
  a01=(a01+a05);
  a05=3.0075286497147785e-01;
  a05=(a05*a06);
  a01=(a01+a05);
  a00=(a00-a01);
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[1]? arg[1][6] : 0;
  a01=arg[0]? arg[0][6] : 0;
  a05=sin(a01);
  a06=arg[0]? arg[0][7] : 0;
  a10=tan(a06);
  a02=(a05*a10);
  a02=(a02*a08);
  a12=(a12+a02);
  a01=cos(a01);
  a10=(a01*a10);
  a10=(a10*a04);
  a12=(a12+a10);
  a00=(a00-a12);
  if (res[0]!=0) res[0][6]=a00;
  a00=arg[1]? arg[1][7] : 0;
  a12=(a01*a08);
  a10=(a05*a04);
  a12=(a12-a10);
  a00=(a00-a12);
  if (res[0]!=0) res[0][7]=a00;
  a00=arg[1]? arg[1][8] : 0;
  a06=cos(a06);
  a05=(a05/a06);
  a05=(a05*a08);
  a01=(a01/a06);
  a01=(a01*a04);
  a05=(a05+a01);
  a00=(a00-a05);
  if (res[0]!=0) res[0][8]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int auv_model_impl_dae_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int auv_model_impl_dae_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int auv_model_impl_dae_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void auv_model_impl_dae_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int auv_model_impl_dae_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void auv_model_impl_dae_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void auv_model_impl_dae_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void auv_model_impl_dae_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int auv_model_impl_dae_fun_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int auv_model_impl_dae_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real auv_model_impl_dae_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* auv_model_impl_dae_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* auv_model_impl_dae_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* auv_model_impl_dae_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    case 5: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* auv_model_impl_dae_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int auv_model_impl_dae_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int auv_model_impl_dae_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
