# OPEN_LOOP           = 0
# POSE_HOLD           = 1
# HEADING_HOLD        = 2
# DEPTH_HEADING_HOLD  = 3
# DEPTH_HOLD          = 4
# POSE_HEADING_HOLD   = 5
# CONTROL_MODE_END    = 6

geometry_msgs/Twist desired_velocity
uint32 control_mode
---
---
