/**:
  ros__parameters:
    target_frame: "orca/odom"
    timer_rate_ms: 200

    track_config:
      default:
        nm:
          confirm_n: 3 # hits needed for confirmation
          confirm_m: 5 # window size for confirmation
          delete_n: 5  # misses needed for deletion
          delete_m: 7  # window size for deletion

        gate:
          min_pos_error: 0.0 # in meters
          max_pos_error: 0.5 # in meters
          min_ori_error: 0.0 # in radians
          max_ori_error: 0.5 # in radians

        dyn_mod_std_dev: 0.2
        sens_mod_std_dev: 0.2

        init_pos_std_dev: 0.1
        init_ori_std_dev: 0.05

        mahalanobis_gate_threshold: 2.5 # in std deviations
        prob_of_detection: 0.5
        clutter_intensity: 0.01

    debug:
      enable: false
      topic_name: "landmark_server/debug/landmark_tracks"
      convergence_landmark_topic: "landmark_server/debug/convergence_landmark"
