reference_frame: start
created_at: '2026-10-09T22:28:11'
objects:
  bin:
    position: [16.5, 4.2, 3.15]
    orientation: [0, 0, -0.7071068, 0.7071068]
  gate:
    position: [4, 0, 2.3]
    orientation: [0, 0, 0, 1]
  octagon:
    position: [19.3, 0.1, 0]
    orientation: [0, 0, -0.7071068, 0.7071068]
  slalom:
    position: [10.1, 0.4, 2.6]
    orientation: [0, 0, 0, 1]
  torpedo:
    position: [17, -5.2, 2.55]
    orientation: [0, 0, 1, 0]
gui_state:
  reference_frame: start
  objects:
    reference:
      position: [4, 12.5, 0]
      orientation: [0, 0, -0.7071068, 0.7071068]
    gate:
      position: [8, 12.5, 0]
      orientation: [0, 0, -0.7071068, 0.7071068]
    slalom:
      position: [14.1, 12.1, 0]
      orientation: [0, 0, -0.7071068, 0.7071068]
    torpedo:
      position: [21, 17.7, 0]
      orientation: [0, 0, 0.7071068, 0.7071068]
    bin:
      position: [20.5, 8.3, 0]
      orientation: [0, 0, 0, 1]
    octagon:
      position: [23.3, 12.4, 0]
      orientation: [0, 0, 0, 1]
