/**:
  ros__parameters:
    K1 : [9.0, 9.0, 11.0, 1.0, 4.5, 4.5] # Outer loop tuning parameters
    K2 : [20.0, 20.0, 25.0, 3.0, 7.5, 7.5] # Inner loop tuning parameters
    r_b_bg : [0.0, 0.0, 0.015] # Vector from body centre to centre of gravity
    adapt_gain : [0.3, 0.05, 0.3, 0.05, 0.3, 0.05, 0.3, 0.05, 0.3, 0.05, 0.3, 0.05] # Tuning parameters for linear and nonlinear damping
    d_gain : [0.4, 0.4, 0.4, 0.4, 0.4, 0.4] # Tuning parameters for the unmodeled disturbances and uncertanties
