/**:
  ros__parameters:
    K1 : [0.1, 0.1, 10.0, 0.1, 0.1, 10.0] # Outer loop tuning parameters
    K2 : [10.0, 10.0, 250.0, 10.0, 10.0, 250.0] # Inner loop tuning parameters
    r_b_bg : [0.01, 0.0, 0.015] # Vector from body centre to centre of gravity
    adapt_gain : [0.1, 0.05, 0.1, 0.05, 0.1, 0.05, 0.1, 0.05, 0.1, 0.05, 0.1, 0.05] # Tuning parameters for linear and nonlinear damping
    d_gain : [0.1, 0.1, 0.1, 0.1, 0.1, 0.1] # Tuning parameters for the unmodeled disturbances and uncertanties
