/**:
  ros__parameters:
    line_sub_topic: "/line_detection/line_segments"
    sonar_info_sub_topic: "/moby/fls/sonar_info"
    line_pub_topic: "/filtered_lines"
    marker_pub_topic: "/filtered_lines_markers"

    target_frame: "moby/odom"
    sonar_frame: "moby/sonar_link"

    timer_rate_ms: 200

    config:
      nm:
        confirm_n: 3 # hits needed for confirmation
        confirm_m: 5 # window size for confirmation
        delete_n: 5  # misses needed for deletion
        delete_m: 7  # window size for deletion

      gate:
        min_rho_error: 1.50    # meters  – below this, gate always passes
        max_rho_error: 1.0    # meters
        min_phi_error: 0.5    # radians – below this, gate always passes
        max_phi_error: 0.5    # radians

      dyn_mod_std_dev: 0.05
      sens_mod_std_dev: 0.1

      init_rho_std_dev: 0.3
      init_phi_std_dev: 0.15

      mahalanobis_gate_threshold: 3.0
      prob_of_detection: 0.5
      clutter_intensity: 0.01

    debug:
      enable: true
      meas_marker_topic: "/line_debug/raw_markers"
      state_marker_topic: "/line_debug/filtered_markers"
