/**:
  ros__parameters:
    Kp_x: 50.0
    Kp_y: 50.0
    Kp_z: 25.0
    Kp_roll: 50.0
    Kp_pitch: 80.0
    Kp_yaw: 50.0
    Ki_x: 0.00
    Ki_y: 0.00
    Ki_z: 0.01
    Ki_roll: 0.07
    Ki_pitch: 0.10
    Ki_yaw: 0.0
    Kd_x: 120.0
    Kd_y: 120.0
    Kd_z: 250.0
    Kd_roll: 90.0
    Kd_pitch: 120.0
    Kd_yaw: 90.0
