/**:
  ros__parameters:
    Kp_x: 40.0
    Kp_y: 40.0
    Kp_z: 40.0
    Kp_roll: 7.5
    Kp_pitch: 11.0
    Kp_yaw: 9.0
    Ki_x: 0.04
    Ki_y: 0.04
    Ki_z: 0.02
    Ki_roll: 0.02
    Ki_pitch: 0.04
    Ki_yaw: 0.02
    Kd_x: 7.5
    Kd_y: 7.5
    Kd_z: 12.5
    Kd_roll: 0.1
    Kd_pitch: 5.0
    Kd_yaw: 0.1
