/**:
  ros__parameters:
    K1 : [12.5, 12.5, 17.5, 3.5, 10.0, 10.0] # Outer loop tuning parameters
    K2 : [40.0, 40.0, 60.0, 25.0, 40.0, 40.0] # Inner loop tuning parameters
    r_b_bg : [0.00, 0.0, 0.015] # Vector from body centre to centre of gravity
    adapt_gain : [0.4, 0.2, 0.4, 0.2, 0.4, 0.2, 0.4, 0.2, 0.4, 0.2, 0.4, 0.2] # Tuning parameters for linear and nonlinear damping
    d_gain : [0.2, 0.2, 0.2, 0.2, 0.2, 0.2] # Tuning parameters for the unmodeled disturbances and uncertanties
    time_step: 10 #Controller timestep in milliseconds (ms)
    singularity_tolerance: 1.0e-8 # Determinant threshold below which L is treated as singular
    adapt_param_max: 15.0 # Symmetric clamp on adaptive damping parameter estimates
    d_est_max: 15.0 # Symmetric clamp on disturbance estimates
