/**:
  eskf_node:
    ros__parameters:
      diag_Q_std: [0.05, 0.05, 0.1, 0.01, 0.01, 0.02, 0.001, 0.001, 0.001, 0.0001, 0.0001, 0.0001]
      diag_p_init: [1.0, 1.0, 1.0, 0.5, 0.5, 0.5, 0.1, 0.1, 0.1, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001]
      transform:
        imu_frame_r: [ 1.0,  0.0,  0.0,
                    0.0, 1.0,  0.0,
                    0.0,  0.0, 1.0 ]
        imu_frame_t: [ 0.0, 0.0, 0.0 ]

        dvl_frame_r: [ 0.0, -1.0,  0.0,
                        1.0,  0.0,  0.0,
                        0.0,  0.0,  1.0 ]

        dvl_frame_t: [ 0.4, 0.0, 0.2 ]

        depth_frame_t: [ 0.0, 0.0, 0.0 ]
      use_tf_transforms: false
      publish_tf: true
      publish_pose: true
      publish_twist: true
      publish_rate_ms: 5
      # biases in the IMU
      add_gravity_to_imu: true
      initial_gyro_bias: [0.0, 0.0, 0.0]
      initial_accel_bias: [3.53e-2, 0.0, -0.0533]
      publish_biases: true
      # environmental parameters
      atmospheric_pressure: 101000.0 # [Pa]
      water_density: 1026.0 # [kg/m3]
      gravity: 9.82841

      use_landmark_egomotion: true
      vo:
        landmarks_topic: /aruco_detector/landmarks

        base_frame: nautilus/base_link
        camera_frame: "/cam/camera_info"

        nis_gate_pose: 16.812
        nis_gate_velocity: 11.345
        disable_gating: true
        dropout_timeout: 10.0
        rejects_limit: 5

        pos_floor: 0.1
        att_floor: 0.05
        vel_floor: 0.4
        dt_min: 0.02
        dt_max: 15.0

        # Sliding-window smoother
        use_sw: true
        window_size: 20
        max_age: 15.0
        huber_deg: 20.0
        gate_deg: 60.0

# USED SENSORS
  # IMU: Kongsberg mini MRU
  # DVL & Depth: Nucleus 1000
