/**:
  ros__parameters:
    # Topics
    line_sub_topic: "/line_detection/line_segments"
    pose_sub_topic: "/pose" #Hente fra dronen senere?
    map_pub_topic: "/map" #skal jeg publishe til map??

    # Publish
    publish_rate_ms: 200

    # Frames / TF

    map_frame: "map"
    odom_frame: "odom"
    base_frame: "base_link"
    sonar_frame: "Orca/FLS"
    enu_to_ned: false

    # Map / grid
    size_x: 1000.0
    size_y: 1000.0
    resolution: 0.1
    frame_id: "map"

    # Map cells
    unknown_cell: -1
    occupied_cell: 100


    # Corner/docking params
    min_dist: 0.0
    max_dist: 1000.0
    angle_threshold: 1.5
    min_angle: 0.7
    max_angle: 3.0
    right_wall_offset: 0.5
    far_wall_offset: 0.5

    # Waypoint
    switching_threshold: 0.5
    overwrite_prior_waypoints: true
    take_priority: true

#TO DO: organisere bedre