#include <ros/ros.h>

#include <dynamic_reconfigure/server.h>
#include <dp_controller/DpControllerConfig.h> //autogenerated from Controller.cfg

void callback(dp_controller::DpControllerConfig &config, uint32_t level) {
  ROS_INFO("Reconfigure Request: %f",
            config.velocity_gain);
}

int main(int argc, char **argv) {
  ros::init(argc, argv, "dp_cfg"); //can move this to DP node

  dynamic_reconfigure::Server<dp_controller::DpControllerConfig> server;
  dynamic_reconfigure::Server<dp_controller::DpControllerConfig>::CallbackType f;

  f = boost::bind(&callback, _1, _2);
  server.setCallback(f);

  ROS_INFO("Spinning node");
  ros::spin();
  return 0;
}