# This file defines parameters specific to Nautilus.
# When looking at the AUV from above, the thruster placement is:
#
#        front
#       |======|
#  |=7↗=|      |=0↖=|
#  |    |      |    |
#  | 6• |      | 1• |
#  |    |      |    |
#  |    |      |    |
#  | 5• |      | 2• |
#  |    |      |    |
#  |=4↘=|==||==|=3↙=|
#

/**:
  ros__parameters:
    physical:
      center_of_mass: [0.0, 0.0, 0.0] # CO is aligned with CM Position (x,y,z) in meters (M)
      mass_matrix: [53.7, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 53.7, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 53.7, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 11.0628, 1.086, -3.17502, 0.0, 0.0, 0.0, 1.086, 23.1128, 0.1025, 0.0, 0.0, 0.0, -3.17502, 0.1025, 26.23998]
      # 6x6 mass_inertia_matrix
    propulsion:
      solver_type: "qp"
      dofs:
        num: 6
      dimensions:
        num: 3
      thrusters:
        num: 8
        thruster_force_direction: [ # Direction of forces X,Y,Z, same logic as thruster_position thruster0 produces thrust in (X0,Y0,Z0) and ||(X0,Y0,Z0)|| = 1
            0.70711,
            0.00000,
            0.00000,
            -0.70711,
            -0.70711,
            0.00000,
            0.00000,
            0.70711, # Surge
            -0.70711,
            0.00000,
            0.00000,
            -0.70711,
            0.70711,
            0.00000,
            0.00000,
            0.70711, # Sway
            0.00000,
            1.00000,
            1.00000,
            0.00000,
            0.00000,
            1.00000,
            1.00000,
            0.00000, # Heave
          ]
        thruster_position: [ # Position (x0,x1 ... x7,y1,y2, ...,y7,z1,z2, ... ,z7) in meters (M). i.e thruster0 has position (x0,y0,z0)
          0.413892,
          0.140095,
          -0.163904,
          -0.413892,
          -0.413892,
          -0.163904,
          0.140095,
          0.413892, # x-positions of the thrusters
          0.313022,
          0.313022,
          0.313022,
          0.313022,
          -0.313022,
          -0.313022,
          -0.313022,
          -0.313022, # y-positions of the thrusters
          0.021736,
          0.021736,
          0.021736,
          0.021736,
          0.021736,
          0.021736,
          0.021736,
          0.021736, # z-positions of the thrusters
        ]

        constraints:
          max_force: 40.0
          min_force: -40.0
          input_matrix_weights: [1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0]
          slack_matrix_weights: [2000.0,2000.0,2000.0,2000.0,2000.0,2000.0]

        rate_of_change:
          max: 1 # Maximum rate of change in newton per second for a thruster

        thrust_update_rate: 100.0 # [Hz]
        watchdog_timeout: 1.0 # [s]
        thruster_to_pin_mapping: [4, 5, 6, 7, 0, 1, 2, 3] # I.e. if thruster_to_pin = [ 7,  6,  5,  4,  3,  2,  1,  0 ] then thruster 0 is pin 1 etc..
        thruster_direction: [1, -1, -1, 1, 1, -1, -1, 1] # Disclose during thruster mapping (+/- 1)
        thruster_PWM_min: [1050, 1050, 1050, 1050, 1050, 1050, 1050, 1050] # Minimum PWM value, Recommended: [1100, 1100, 1100, 1100, 1100, 1100, 1100, 1100]
        thruster_PWM_max: [1950, 1950, 1950, 1950, 1950, 1950, 1950, 1950] # Maximum PWM value, Recommended: [1900, 1900, 1900, 1900, 1900, 1900, 1900, 1900]

    topics:
      wrench_input: "wrench_input"
      thruster_forces: "thruster_forces"
      pwm_output: "pwm"
      current: "power_sense_module/current"
      voltage: "power_sense_module/voltage"
      pressure: "pressure"
      temperature: "temperature"
      joy: "joy"
      pose: "pose"
      twist: "twist"
      odom: "odom"
      operation_mode: "operation_mode"
      killswitch: "killswitch"
      reference_pose: "reference_pose"
      landmarks: "landmarks"
      waypoint: "waypoint"
      guidance:
        los: "guidance/los"
        dp: "guidance/dp"
      dvl_twist: "dvl/twist"
      dvl_altitude: "dvl/altitude"
      imu: "imu/data_raw"
      sonar_info: "fls/sonar_info"
      pressure_sensor: "pressure_sensor"
      gripper_servos: "gripper_servos"


    action_servers:
      reference_filter: "reference_filter"
      los: "los_guidance"
      landmark_polling: "landmark_polling"
      landmark_convergence: "landmark_convergence"
      waypoint_manager: "waypoint_manager"

    services:
      set_operation_mode: "set_operation_mode"
      set_killswitch: "set_killswitch"
      toggle_killswitch: "toggle_killswitch"
      get_operation_mode: "get_operation_mode"
      waypoint_addition: "waypoint_addition"
      start_mission: "start_mission"
