on:
  push:
    tags:
      - 'v*'
jobs:
  docker-ros:
    runs-on: ubuntu-latest
    steps:
      - uses: ika-rwth-aachen/docker-ros@v1.6.1
        with:
          base-image: rwthika/ros2:humble
          target: dev  # Specify the dev stage
          image-tag: ${{ github.ref_name }}
          platform: linux/arm64,linux/amd64
