name: Build and Push Docker Image

on:
  push:
    branches:
      - feat/docker_export

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: download vcs
        run: |
          sudo apt update
          pip3 install vcstool

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: build ws and run script
        run: | 
          cd ..
          mkdir -p ./ros2_ws/src
          cp -r vortex-auv ./ros2_ws/src/vortex-auv
          cd ros2_ws
          vcs import src < ./src/vortex-auv/dependencies.repos
          chmod +x ./src/vortex-auv/docker/build.sh
          ./src/vortex-auv/docker/build.sh

      - name: Retag Docker image for GitHub Container Registry
        run: |
          docker tag auv-image:latest ghcr.io/${{ github.repository_owner }}/auv-image:latest

      - name: Push Docker image to GitHub Container Registry
        run: |
            docker push ghcr.io/${{ github.repository_owner }}/auv-image:latest