name: Build and Push Docker Image

on:
  push:
    branches:
      - feat/docker_export

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run build script
        run: |
          chmod +x ./build.sh
          ./build.sh

      - name: Retag Docker image for GitHub Container Registry
        run: |
          docker tag auv-image:latest ghcr.io/${{ github.repository_owner }}/auv-image:latest

      - name: Push Docker image to GitHub Container Registry
        run: |
            docker push ghcr.io/${{ github.repository_owner }}/auv-image:latest