name: Source Build
# Build the ROS 2 workspace from source code and run tests
on:
  workflow_dispatch:
  pull_request:
  # Runs daily to check for dependency issues or flaking tests
  schedule:
    - cron: "0 1 * * *"
jobs:
  source-build:
    uses: vortexntnu/vortex-ci/.github/workflows/reusable-source-build.yaml@main
    with:
      ros_distro: 'humble'
      os_name: 'ubuntu-22.04'
      ref: ${{ github.ref }}
      vcs_repo_file_url: 'https://raw.githubusercontent.com/vortexntnu/vortex-auv/main/ros2.repos'
      dependency_script: 'requirements.sh'
